# Generated by Django 5.0.6 on 2024-06-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotgrafia',
            new_name='data_fotografia',
        ),
    ]
