# Generated by Django 5.0.6 on 2024-06-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_rename_data_fotgrafia_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
